//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryServiceBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaundryServiceBot.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requet for PickUp.
        /// </summary>
        internal static string BtnBookService {
            get {
                return ResourceManager.GetString("BtnBookService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Card.
        /// </summary>
        internal static string BtnRatecard {
            get {
                return ResourceManager.GetString("BtnRatecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the Launadry Date for PickUp.
        /// </summary>
        internal static string DateHeading {
            get {
                return ResourceManager.GetString("DateHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Selct Bleow option if pickup is Today/Tommorw if not Enter date in format(dd/mm/yyyy eg: 20/02/2017).
        /// </summary>
        internal static string DateSelction {
            get {
                return ResourceManager.GetString("DateSelction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNADRY SERVICE.
        /// </summary>
        internal static string HeadingTitle {
            get {
                return ResourceManager.GetString("HeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to On-Demand Laundry &amp; Dry Cleaning Service Bot.Convenience delivered to your Doorstep.
        /// </summary>
        internal static string IntdoTxt {
            get {
                return ResourceManager.GetString("IntdoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to On-Demand Laundry &amp; Dry Cleaning Service.Please Select Below Options.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the Preffered time Slot for example (16:00\18:00).
        /// </summary>
        internal static string TimeHeading {
            get {
                return ResourceManager.GetString("TimeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string TxtToday {
            get {
                return ResourceManager.GetString("TxtToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string TxtTommrow {
            get {
                return ResourceManager.GetString("TxtTommrow", resourceCulture);
            }
        }
    }
}
